---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.17
  commands:
    - sh scripts/build.sh

- name: publish_amd64
  image: plugins/docker:latest
  settings:
    auto_tag: true
    auto_tag_suffix: linux-amd64
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: wssio/drone-vault
  when:
    branch:
      - main
    event:
      - push
      - tag

- name: publish_arm64
  image: plugins/docker:latest
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm64
    dockerfile: docker/Dockerfile.linux.arm64
    password:
      from_secret: docker_password
    repo: wssio/drone-vault
    username:
      from_secret: docker_username
  when:
    branch:
      - main
    event:
      - push
      - tag

- name: publish_arm
  image: plugins/docker:latest
  settings:
    auto_tag: true
    auto_tag_suffix: linux-arm
    dockerfile: docker/Dockerfile.linux.arm
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: wssio/drone-vault
  when:
    branch:
      - main
    event:
      - push
      - tag
